spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  servlet:
    multipart:
      # max file size
      max-file-size: 10MB
      # max request size
      max-request-size: 10MB
server:
  error:
    include-message: always
# files storage location (stores all files uploaded via REST API)
storage:
  location: ./webapps/cs/uploads
